/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dataObjects.Pokemon;
import data_access_objects.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edward
 */
public class trainerMainFrame extends javax.swing.JFrame {
    int tid;
    /**
     * Creates new form pokeMainFrame
     */
    public trainerMainFrame(int tid) {
        initComponents();
        this.tid = tid;
        this.welcomeLabel.setText("Welcome to Trainer's Panel, Trainer "+ this.tid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        displayPokemonButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        depositButton = new javax.swing.JButton();
        pickUpButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        tradeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Trainer's Panel, Welcome Trainer!");
        welcomeLabel.setToolTipText("");

        displayPokemonButton.setText("Show Your Pokemons");
        displayPokemonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPokemonButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        depositButton.setText("Deposit Selected Pokmeon");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        pickUpButton.setText("View and Pick up Deposited Pokemon");
        pickUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpButtonActionPerformed(evt);
            }
        });

        transferButton.setText("Transfer Pokemon");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        tradeButton.setText("Trade");
        tradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tradeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(displayPokemonButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pickUpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transferButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tradeButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayPokemonButton)
                    .addComponent(depositButton)
                    .addComponent(pickUpButton)
                    .addComponent(transferButton)
                    .addComponent(tradeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayPokemonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPokemonButtonActionPerformed
        // TODO add your handling code here:
        TrainerController tc;
        tc = TrainerController.getInstance();
        List<Pokemon> pkm = tc.getPokemons(this.tid);
     

        
        DefaultTableModel pkmModel = new DefaultTableModel(){
            @Override
            public String getColumnName(int index) {
                String[] columnNames = {"Pokemon Id", "Name", "CP","HP","Pokeball Type"};
                return columnNames[index];
            }
        };
        pkmModel.setColumnCount(5);
        for(int i =0;i<pkm.size();i++)
        {
           Object[] pkmData= {pkm.get(i).getPid(),pkm.get(i).getPname(), pkm.get(i).getCp(), pkm.get(i).getHP(),pkm.get(i).getPokeball()};
           pkmModel.addRow(pkmData);
        }

         this.jTable1.setModel(pkmModel);
         pkmModel.fireTableDataChanged();
         this.jTable1.setEnabled(true);
         this.depositButton.setEnabled(true);
         this.pickUpButton.setEnabled(true);
         this.displayPokemonButton.setEnabled(true);
         this.tradeButton.setEnabled(true);
         this.transferButton.setEnabled(true);
        
    }//GEN-LAST:event_displayPokemonButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
       int selected_row = this.jTable1.getSelectedRow();
       Object selected_pid = this.jTable1.getModel().getValueAt(selected_row, 0);
       depositDialog dg = new depositDialog(this, true,(int) selected_pid, this.tid);
       dg.setVisible(true);
      this.jTable1.setEnabled(false);
       
    }//GEN-LAST:event_depositButtonActionPerformed

    private void pickUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpButtonActionPerformed
        // TODO add your handling code here:
        returnPokemon rtD = new returnPokemon(this,true, this.tid);
        rtD.setVisible(true);
        this.jTable1.setEnabled(false);
    }//GEN-LAST:event_pickUpButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
       int selected_row = this.jTable1.getSelectedRow();
       Object selected_pid = this.jTable1.getModel().getValueAt(selected_row, 0);
       if((int) selected_row>=0){
       TransferDialog tfD = new TransferDialog(this, true,(int) selected_pid, this.tid);
       tfD.setVisible(true);
       this.jTable1.setEnabled(false);
       }

    }//GEN-LAST:event_transferButtonActionPerformed

    private void tradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tradeButtonActionPerformed
        // TODO add your handling code here:
       int selected_row = this.jTable1.getSelectedRow();
       Object selected_pid = this.jTable1.getModel().getValueAt(selected_row, 0);
       if((int) selected_row>=0){
       TradeDialog tfD = new TradeDialog(this, true,(int) selected_pid, this.tid, "Trainer");
       tfD.setVisible(true);
        this.jTable1.setEnabled(false);}
    }//GEN-LAST:event_tradeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depositButton;
    private javax.swing.JButton displayPokemonButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pickUpButton;
    private javax.swing.JButton tradeButton;
    private javax.swing.JButton transferButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}

